/**
 * Country.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {
seedData:[
{id:1,countryCode:'AF',country:'Afghanistan'},
{id:2,countryCode:'AL',country:'Albania'},
{id:3,countryCode:'DZ',country:'Algeria'},
{id:4,countryCode:'AS',country:'American Samoa'},
{id:5,countryCode:'AD',country:'Andorra'},
{id:6,countryCode:'AO',country:'Angola'},
{id:7,countryCode:'AI',country:'Anguilla'},
{id:8,countryCode:'AQ',country:'Antarctica'},
{id:9,countryCode:'AG',country:'Antigua And Barbuda'},
{id:10,countryCode:'AR',country:'Argentina'},
{id:11,countryCode:'AM',country:'Armenia'},
{id:12,countryCode:'AW',country:'Aruba'},
{id:13,countryCode:'AU',country:'Australia'},
{id:14,countryCode:'AT',country:'Austria'},
{id:15,countryCode:'AZ',country:'Azerbaijan'},
{id:16,countryCode:'BS',country:'Bahamas The'},
{id:17,countryCode:'BH',country:'Bahrain'},
{id:18,countryCode:'BD',country:'Bangladesh'},
{id:19,countryCode:'BB',country:'Barbados'},
{id:20,countryCode:'BY',country:'Belarus'},
{id:21,countryCode:'BE',country:'Belgium'},
{id:22,countryCode:'BZ',country:'Belize'},
{id:23,countryCode:'BJ',country:'Benin'},
{id:24,countryCode:'BM',country:'Bermuda'},
{id:25,countryCode:'BT',country:'Bhutan'},
{id:26,countryCode:'BO',country:'Bolivia'},
{id:27,countryCode:'BA',country:'Bosnia and Herzegovina'},
{id:28,countryCode:'BW',country:'Botswana'},
{id:29,countryCode:'BV',country:'Bouvet Island'},
{id:30,countryCode:'BR',country:'Brazil'},
{id:31,countryCode:'IO',country:'British Indian Ocean Territory'},
{id:32,countryCode:'BN',country:'Brunei'},
{id:33,countryCode:'BG',country:'Bulgaria'},
{id:34,countryCode:'BF',country:'Burkina Faso'},
{id:35,countryCode:'BI',country:'Burundi'},
{id:36,countryCode:'KH',country:'Cambodia'},
{id:37,countryCode:'CM',country:'Cameroon'},
{id:38,countryCode:'CA',country:'Canada'},
{id:39,countryCode:'CV',country:'Cape Verde'},
{id:40,countryCode:'KY',country:'Cayman Islands'},
{id:41,countryCode:'CF',country:'Central African Republic'},
{id:42,countryCode:'TD',country:'Chad'},
{id:43,countryCode:'CL',country:'Chile'},
{id:44,countryCode:'CN',country:'China'},
{id:45,countryCode:'CX',country:'Christmas Island'},
{id:46,countryCode:'CC',country:'Cocos (Keeling'},
{id:47,countryCode:'CO',country:'Colombia'},
{id:48,countryCode:'KM',country:'Comoros'},
{id:49,countryCode:'CG',country:'Congo'},
{id:50,countryCode:'CD',country:'Congo The Democratic Republic Of The'},
{id:51,countryCode:'CK',country:'Cook Islands'},
{id:52,countryCode:'CR',country:'Costa Rica'},
{id:53,countryCode:'CI',country:'Cote D Ivoire (Ivory Coast)'},
{id:54,countryCode:'HR',country:'Croatia (Hrvatska'},
{id:55,countryCode:'CU',country:'Cuba'},
{id:56,countryCode:'CY',country:'Cyprus'},
{id:57,countryCode:'CZ',country:'Czech Republic'},
{id:58,countryCode:'DK',country:'Denmark'},
{id:59,countryCode:'DJ',country:'Djibouti'},
{id:60,countryCode:'DM',country:'Dominica'},
{id:61,countryCode:'DO',country:'Dominican Republic'},
{id:62,countryCode:'TP',country:'East Timor'},
{id:63,countryCode:'EC',country:'Ecuador'},
{id:64,countryCode:'EG',country:'Egypt'},
{id:65,countryCode:'SV',country:'El Salvador'},
{id:66,countryCode:'GQ',country:'Equatorial Guinea'},
{id:67,countryCode:'ER',country:'Eritrea'},
{id:68,countryCode:'EE',country:'Estonia'},
{id:69,countryCode:'ET',country:'Ethiopia'},
{id:70,countryCode:'XA',country:'External Territories of Australia'},
{id:71,countryCode:'FK',country:'Falkland Islands'},
{id:72,countryCode:'FO',country:'Faroe Islands'},
{id:73,countryCode:'FJ',country:'Fiji Islands'},
{id:74,countryCode:'FI',country:'Finland'},
{id:75,countryCode:'FR',country:'France'},
{id:76,countryCode:'GF',country:'French Guiana'},
{id:77,countryCode:'PF',country:'French Polynesia'},
{id:78,countryCode:'TF',country:'French Southern Territories'},
{id:79,countryCode:'GA',country:'Gabon'},
{id:80,countryCode:'GM',country:'Gambia The'},
{id:81,countryCode:'GE',country:'Georgia'},
{id:82,countryCode:'DE',country:'Germany'},
{id:83,countryCode:'GH',country:'Ghana'},
{id:84,countryCode:'GI',country:'Gibraltar'},
{id:85,countryCode:'GR',country:'Greece'},
{id:86,countryCode:'GL',country:'Greenland'},
{id:87,countryCode:'GD',country:'Grenada'},
{id:88,countryCode:'GP',country:'Guadeloupe'},
{id:89,countryCode:'GU',country:'Guam'},
{id:90,countryCode:'GT',country:'Guatemala'},
{id:91,countryCode:'XU',country:'Guernsey and Alderney'},
{id:92,countryCode:'GN',country:'Guinea'},
{id:93,countryCode:'GW',country:'Guinea-Bissau'},
{id:94,countryCode:'GY',country:'Guyana'},
{id:95,countryCode:'HT',country:'Haiti'},
{id:96,countryCode:'HM',country:'Heard and McDonald Islands'},
{id:97,countryCode:'HN',country:'Honduras'},
{id:98,countryCode:'HK',country:'Hong Kong S.A.R.'},
{id:99,countryCode:'HU',country:'Hungary'},
{id:100,countryCode:'IS',country:'Iceland'},
{id:101,countryCode:'IN',country:'India'},
{id:102,countryCode:'ID',country:'Indonesia'},
{id:103,countryCode:'IR',country:'Iran'},
{id:104,countryCode:'IQ',country:'Iraq'},
{id:105,countryCode:'IE',country:'Ireland'},
{id:106,countryCode:'IL',country:'Israel'},
{id:107,countryCode:'IT',country:'Italy'},
{id:108,countryCode:'JM',country:'Jamaica'},
{id:109,countryCode:'JP',country:'Japan'},
{id:110,countryCode:'XJ',country:'Jersey'},
{id:111,countryCode:'JO',country:'Jordan'},
{id:112,countryCode:'KZ',country:'Kazakhstan'},
{id:113,countryCode:'KE',country:'Kenya'},
{id:114,countryCode:'KI',country:'Kiribati'},
{id:115,countryCode:'KP',country:'Korea North'},
{id:116,countryCode:'KR',country:'Korea South'},
{id:117,countryCode:'KW',country:'Kuwait'},
{id:118,countryCode:'KG',country:'Kyrgyzstan'},
{id:119,countryCode:'LA',country:'Laos'},
{id:120,countryCode:'LV',country:'Latvia'},
{id:121,countryCode:'LB',country:'Lebanon'},
{id:122,countryCode:'LS',country:'Lesotho'},
{id:123,countryCode:'LR',country:'Liberia'},
{id:124,countryCode:'LY',country:'Libya'},
{id:125,countryCode:'LI',country:'Liechtenstein'},
{id:126,countryCode:'LT',country:'Lithuania'},
{id:127,countryCode:'LU',country:'Luxembourg'},
{id:128,countryCode:'MO',country:'Macau S.A.R.'},
{id:129,countryCode:'MK',country:'Macedonia'},
{id:130,countryCode:'MG',country:'Madagascar'},
{id:131,countryCode:'MW',country:'Malawi'},
{id:132,countryCode:'MY',country:'Malaysia'},
{id:133,countryCode:'MV',country:'Maldives'},
{id:134,countryCode:'ML',country:'Mali'},
{id:135,countryCode:'MT',country:'Malta'},
{id:136,countryCode:'XM',country:'Man (Isle of'},
{id:137,countryCode:'MH',country:'Marshall Islands'},
{id:138,countryCode:'MQ',country:'Martinique'},
{id:139,countryCode:'MR',country:'Mauritania'},
{id:140,countryCode:'MU',country:'Mauritius'},
{id:141,countryCode:'YT',country:'Mayotte'},
{id:142,countryCode:'MX',country:'Mexico'},
{id:143,countryCode:'FM',country:'Micronesia'},
{id:144,countryCode:'MD',country:'Moldova'},
{id:145,countryCode:'MC',country:'Monaco'},
{id:146,countryCode:'MN',country:'Mongolia'},
{id:147,countryCode:'MS',country:'Montserrat'},
{id:148,countryCode:'MA',country:'Morocco'},
{id:149,countryCode:'MZ',country:'Mozambique'},
{id:150,countryCode:'MM',country:'Myanmar'},
{id:151,countryCode:'NA',country:'Namibia'},
{id:152,countryCode:'NR',country:'Nauru'},
{id:153,countryCode:'NP',country:'Nepal'},
{id:154,countryCode:'AN',country:'Netherlands Antilles'},
{id:155,countryCode:'NL',country:'Netherlands The'},
{id:156,countryCode:'NC',country:'New Caledonia'},
{id:157,countryCode:'NZ',country:'New Zealand'},
{id:158,countryCode:'NI',country:'Nicaragua'},
{id:159,countryCode:'NE',country:'Niger'},
{id:160,countryCode:'NG',country:'Nigeria'},
{id:161,countryCode:'NU',country:'Niue'},
{id:162,countryCode:'NF',country:'Norfolk Island'},
{id:163,countryCode:'MP',country:'Northern Mariana Islands'},
{id:164,countryCode:'NO',country:'Norway'},
{id:165,countryCode:'OM',country:'Oman'},
{id:166,countryCode:'PK',country:'Pakistan'},
{id:167,countryCode:'PW',country:'Palau'},
{id:168,countryCode:'PS',country:'Palestinian Territory Occupied'},
{id:169,countryCode:'PA',country:'Panama'},
{id:170,countryCode:'PG',country:'Papua new Guinea'},
{id:171,countryCode:'PY',country:'Paraguay'},
{id:172,countryCode:'PE',country:'Peru'},
{id:173,countryCode:'PH',country:'Philippines'},
{id:174,countryCode:'PN',country:'Pitcairn Island'},
{id:175,countryCode:'PL',country:'Poland'},
{id:176,countryCode:'PT',country:'Portugal'},
{id:177,countryCode:'PR',country:'Puerto Rico'},
{id:178,countryCode:'QA',country:'Qatar'},
{id:179,countryCode:'RE',country:'Reunion'},
{id:180,countryCode:'RO',country:'Romania'},
{id:181,countryCode:'RU',country:'Russia'},
{id:182,countryCode:'RW',country:'Rwanda'},
{id:183,countryCode:'SH',country:'Saint Helena'},
{id:184,countryCode:'KN',country:'Saint Kitts And Nevis'},
{id:185,countryCode:'LC',country:'Saint Lucia'},
{id:186,countryCode:'PM',country:'Saint Pierre and Miquelon'},
{id:187,countryCode:'VC',country:'Saint Vincent And The Grenadines'},
{id:188,countryCode:'WS',country:'Samoa'},
{id:189,countryCode:'SM',country:'San Marino'},
{id:190,countryCode:'ST',country:'Sao Tome and Principe'},
{id:191,countryCode:'SA',country:'Saudi Arabia'},
{id:192,countryCode:'SN',country:'Senegal'},
{id:193,countryCode:'RS',country:'Serbia'},
{id:194,countryCode:'SC',country:'Seychelles'},
{id:195,countryCode:'SL',country:'Sierra Leone'},
{id:196,countryCode:'SG',country:'Singapore'},
{id:197,countryCode:'SK',country:'Slovakia'},
{id:198,countryCode:'SI',country:'Slovenia'},
{id:199,countryCode:'XG',country:'Smaller Territories of the UK'},
{id:200,countryCode:'SB',country:'Solomon Islands'},
{id:201,countryCode:'SO',country:'Somalia'},
{id:202,countryCode:'ZA',country:'South Africa'},
{id:203,countryCode:'GS',country:'South Georgia'},
{id:204,countryCode:'SS',country:'South Sudan'},
{id:205,countryCode:'ES',country:'Spain'},
{id:206,countryCode:'LK',country:'Sri Lanka'},
{id:207,countryCode:'SD',country:'Sudan'},
{id:208,countryCode:'SR',country:'Suriname'},
{id:209,countryCode:'SJ',country:'Svalbard And Jan Mayen Islands'},
{id:210,countryCode:'SZ',country:'Swaziland'},
{id:211,countryCode:'SE',country:'Sweden'},
{id:212,countryCode:'CH',country:'Switzerland'},
{id:213,countryCode:'SY',country:'Syria'},
{id:214,countryCode:'TW',country:'Taiwan'},
{id:215,countryCode:'TJ',country:'Tajikistan'},
{id:216,countryCode:'TZ',country:'Tanzania'},
{id:217,countryCode:'TH',country:'Thailand'},
{id:218,countryCode:'TG',country:'Togo'},
{id:219,countryCode:'TK',country:'Tokelau'},
{id:220,countryCode:'TO',country:'Tonga'},
{id:221,countryCode:'TT',country:'Trinidad And Tobago'},
{id:222,countryCode:'TN',country:'Tunisia'},
{id:223,countryCode:'TR',country:'Turkey'},
{id:224,countryCode:'TM',country:'Turkmenistan'},
{id:225,countryCode:'TC',country:'Turks And Caicos Islands'},
{id:226,countryCode:'TV',country:'Tuvalu'},
{id:227,countryCode:'UG',country:'Uganda'},
{id:228,countryCode:'UA',country:'Ukraine'},
{id:229,countryCode:'AE',country:'United Arab Emirates'},
{id:230,countryCode:'GB',country:'United Kingdom'},
{id:231,countryCode:'US',country:'United States'},
{id:232,countryCode:'UM',country:'United States Minor Outlying Islands'},
{id:233,countryCode:'UY',country:'Uruguay'},
{id:234,countryCode:'UZ',country:'Uzbekistan'},
{id:235,countryCode:'VU',country:'Vanuatu'},
{id:236,countryCode:'VA',country:'Vatican City State (Holy See'},
{id:237,countryCode:'VE',country:'Venezuela'},
{id:238,countryCode:'VN',country:'Vietnam'},
{id:239,countryCode:'VG',country:'Virgin Islands (British'},
{id:240,countryCode:'VI',country:'Virgin Islands (US'},
{id:241,countryCode:'WF',country:'Wallis And Futuna Islands'},
{id:242,countryCode:'EH',country:'Western Sahara'},
{id:243,countryCode:'YE',country:'Yemen'},
{id:244,countryCode:'YU',country:'Yugoslavia'},
{id:245,countryCode:'ZM',country:'Zambia'},
{id:246,countryCode:'ZW',country:'Zimbabwe'}
],
  attributes: {

  }
};

