module.exports = {
    attributes:{
        hotelUserComments:{
            collection:'HotelUserComment',
            via:'hotel'
        },
        hotelUserRating:{
            collection:'HotelUserRating',
            via:'hotel'
        },
        provider:{
            type:'string',
            notNull:true,
            required:true
        },
        hotelImages:{
            collection:'HotelImage',
            via:'hotel'
        },
        hotelTags:{
            collection:'HotelTag',
            via:'hotels'
        },
        hotelAmenities:{
            collection:'HotelAmenities',
            via:'hotels'
        },
        hotelSales:{
            collection:'HotelSale',
            via:'hotel'
        },
        user:{
            model:'user',
            defaultsTo:null
        },
        hotelName:{
            type:'string',
            notNull:true,
            required:true
        },
        description:{
            type:'string',
            notNull:true,
            required:true
        },
        popularity:{
            type:'string'
        },
        longitude:{
            type:'string',
            notNull:true,
            required:true
        },
        imageHostUrl:{
            type:'string'
        },
        detailsUrl:{
            type:'string'
        },
        latitude:{
            type:'string',
            notNull:true,
            required:true
        },
        callingCode:{
            type:'string',
        },
        phoneNumber:{
            type:'string',
        },
        mobileNumber:{
           type:'string',
        },
        starRating:{
            type:'integer',
            notNull:true
        },
        address:{
            type:'string',
        }
    }
}