module.exports = {
    attributes:{
        checkInDate:{
            type:'date',
            notNull:true,
            required:true
        },
        checkOutDate:{
            type:'date',
            notNull:true,
            required:true
        },
        numberOfGuests:{
            type:'integer',
            notNull:true,
            required:true
        },
        numberOfRooms:{
            type:'integer',
            notNull:true,
            required:true
        },
        saleType:{
            type:'string',
            notNull:true,
            required:true
        },
        status:{
            type:'string',
            notNull:true,
            required:true
        },
        curentWinner:{
            model:'user'
        },
        prices:{
            collection:'HotelPrices',
            via:'hotelSale'
        },
        bids:{
            collection:'HotelBid',
            via:'hotelSale'
        },
        hotel:{
            model:'hotel',
            required:true,
            notNull:true
        }
    }
}