module.exports = {
    attributes:{
        bidAmount:{
            type:'float',
            notNull:true,
            required:true
        },
        currency:{
            type:'string',
            notNull:true,
            required:true
        },
        hotelSale:{
            model:'HotelSale',
            notNull:true,
            required:true
        },
        user:{
            model:'user',
            notNull:true,
            required:true
        }
    }
}