module.exports = {
    companyName:{
      type:'string',
      notNull:true,
      required:true
    },
    mobile:{
      type:'string',
      notNull:true,
      required:true
    },
    work:{
      type:'string',
      notNull:true,
      required:true
    },
    address:{
      type:'string',
      notNull:true,
      required:true
    },
    email:{
      type:'string',
      notNull:true,
      required:true
    }
}
